### ISSUE TITLE
[Feature request] Manual override of device type

### ISSUE THREAD

**Issue by Giorgi020** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#100]
Hi, I really like the automatic discovery and classification of devices (RGB/RGBW/RGBWW), but I recently started using an RGBWW controller for a white strip (and I plan to use it for both warm and cold white in the near future) because I simply had it laying around.

So would it be possible to set a manual type for the device in order to control it as a single channel device, or eventually any subset of available channels (eg. RGB/WW with a temperature wheel/W with a slider/etc from an RGBWW device)?

Thank you a lot for your work!!

**Comment by Zacknetic** [comment]
There has been work to implement a feature such as this, however it would honestly need a rewrite of a large portion of the code base to work well enough for me to release it. As is, that feature often causes system breaking bugs (as in requiring to purge all Magichome devices and start from scratch). Thus, I cannot release it in it's current form.

I'm not sure how long you have been using this plugin @Giorgi020 , but I have been absent for the past 7 months preparing for a career change into software development. The collaborator I tasked with maintaining this plugin has ghosted since February. I will not have time to implement this or any other features until my job search ends.

I am always looking out for pull requests, but that too takes much time. I will keep this thread open for 48 hrs but will close it as wontFix. For now. If that changes I will re-open.

**Comment by Giorgi020** [comment]
Don't worry, I really hope your search will be successful. Thank you!

**Comment by Zacknetic** [comment]
> Don't worry, I really hope your search will be successful. Thank you!

Thank you. Really appreciate you saying so.
