### ISSUE TITLE
Not working with RGBCW Bulbs

### ISSUE THREAD

**Issue by hemijj** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#6]
I have the newer MagicHome RGBCW bulbs that have RGB plus Cool White and Warm White in the same bulb and can only get the functions for the RGB and Cool White. Any support for the Warm White in the Plug-In?

**Comment by Zacknetic** [comment]
Yes it’s supported. Before you renamed it, what was the name given to your lights by the plugin in HomeKit? Also, is your config set to default values?

First and foremost, the way to control the cool white and warm white is to bring the reticle near the center. The closer you are to cyan, the higher cool white. The closer you to red, the higher the warm white. 

If that doesn’t work read below.

Can you enable debug logs, restart homebridge, move the reticle from cyan to red on the color wheel, and upload your homebridge.log here?

I will be able to view the type assigned and figure out why you get the weird behavior. My guess is your device sends the code of a 4 channel device instead of a 5 channel device. Each device sends a primary type and a secondary type. Perhaps haven’t encountered your devices secondary type before.

**Comment by hemijj** [comment]
They were both labeled 7. Thanks for the help and awesome plugin. It was my use of the interface that was the issue, I was able to see both the whites now.

**Comment by hemijj** [comment]
One other question if I may. On the older MagicHome-Platform, I was able to manually specify the IP of the bulb. This allowed me to keep the bulbs on my IOT VLAN and my Homebridge server on my normal VLAN. I have them on the same now, but like keeping these bulbs isolated. Any way to define them that way in this plug-in. Not a big worry, just figured I would ask.

**Comment by Zacknetic** [comment]
Awesome to hear. I have just updated the plugin with a blacklist feature per your. It's not exactly what you are looking for in terms of adding specific bulbs but can be easily expanded into a whitelist feature as well. Let me know if this works for you.

Please update the plugin and edit the settings in Config UI X at the bottom to add blacklisted Unique IDs / MAC Addresses. The read-me has updated information about this but please reply here if you have any questions / concerns.

**Comment by Zacknetic** [comment]
Scratch that, decided to add whitelist capabilities too. Update again if necessary.
